name: Deploy Preview for Pull Requests

on:
  pull_request:
    paths:
      - "**/index.html" # Trigger when any index.html file is modified

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Directory containing the built files (e.g., root or 'dist/')
          publish_branch: gh-pages
          force_orphan: true # Create gh-pages if it doesn't exist

      - name: Post Preview Link as Comment
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          PREVIEW_URL=https://${{ github.repository_owner }}.github.io/${{ github.repository }}/index.html
          COMMENT_BODY="Deployed preview is available at: [Preview Link](${PREVIEW_URL})"

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"${COMMENT_BODY}\"}" \
            https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments
