name: Deploy Preview

on:
  pull_request:
    paths:
      - '**/*index.html'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep 'index.html$')
          for file in $CHANGED_FILES; do
            DIR=$(dirname "$file")
            echo "Deploying $file"
            DEPLOY_URL=$(vercel deploy --token="$VERCEL_TOKEN" "$DIR" --confirm)
            echo "$file deployed to $DEPLOY_URL"
            echo "preview_url_$DIR=$DEPLOY_URL" >> $GITHUB_OUTPUT
          done

      - name: Comment PR
        uses: actions/github-script@v6
        if: success()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const outputFile = process.env.GITHUB_OUTPUT;
            const output = fs.readFileSync(outputFile, 'utf8');
            const deployments = output.split('\n')
              .filter(line => line.startsWith('preview_url_'))
              .map(line => {
                const [key, value] = line.split('=');
                const dir = key.replace('preview_url_', '');
                return `- ${dir}/index.html: ${value}`;
              })
              .join('\n');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview deployments:\n${deployments}`
            })

