name: Deploy Preview for Pull Requests

on:
  pull_request:
    paths:
      - "index.html" # Trigger the workflow only if index.html is modified or added

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js (optional, if needed for building)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies (if needed for build tools)
        run: |
          npm install

      - name: Build Site (if required)
        run: |
          npm run build # Modify this based on your build process

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Replace with the directory containing your index.html if it's not in the root
          publish_branch: gh-pages

      - name: Post Preview Link as Comment
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          PREVIEW_URL=https://${{ github.repository_owner }}.github.io/${{ github.repository }}/index.html
          COMMENT_BODY="Deployed preview is available at: [Preview Link](${PREVIEW_URL})"

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"${COMMENT_BODY}\"}" \
            https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments
